services:
  - type: web
    name: your-app-name
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    startCommand: npm run start
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
